### ISSUE TITLE
Installer build process updates

### ISSUE THREAD

**Issue by chrisroberts** [hashicorp/vagrant-installers#151]
TODO list for issues encountered during end to end release process:

- [x] Add env var check to force requirement of signing (hashicorp/vagrant#10934)
- [x] Add job to validate shasum values to prevent stale files (https://github.com/hashicorp/vagrant/issues/10934#issuecomment-506142135)
- [x] Always remove shasum and sig file before running sign job (https://github.com/hashicorp/vagrant/issues/10934#issuecomment-506142135)
- [ ] Automatic changelog update and tag creation on version modification (hashicorp/vagrant#10930)
